language: generic
sudo: required
services:
  - docker
before_install:
    - docker build -t binoyjayan/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true binoyjayan/docker-react npm run test -- --coverage


