language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t binoyjayan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true binoyjayan/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker1"
  env: "Docker1-env"
  bucket_name: "elasticbeanstalk-us-west-1-427835269791"
  bucket_path: "docker1"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

